version: 1.0.{build}
os:
- Visual Studio 2015

install:
  - git submodule update --init --recursive
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      $travisUtilsVersion = "33"
      $localPath = "$env:USERPROFILE\.local"
      $travisUtilsPath = "$localPath\travis-utils-$travisUtilsVersion"
      if (Test-Path $travisUtilsPath)
      {
        echo "Reusing the Travis Utils version $travisUtilsVersion already downloaded under $travisUtilsPath"
      }
      else
      {
        $url = "https://github.com/SonarSource/travis-utils/archive/v$travisUtilsVersion.zip"
        echo "Downloading Travis Utils version $travisUtilsVersion from $url into $localPath"
        FetchAndUnzip $url $localPath
      }
      $mavenLocal = "$env:USERPROFILE\.m2"
      if (-not(Test-Path $mavenLocal))
      {
        mkdir $mavenLocal | Out-Null
      }
      echo "Installating Travis Utils public Maven settings.xml into $mavenLocal"
      Copy-Item "$travisUtilsPath\m2\settings-public.xml" "$mavenLocal\settings.xml"
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET M2_HOME=C:\maven\apache-maven-3.2.5\

cache:
  - C:\sonarqube\downloads -> appveyor.yml
  - C:\users\appveyor\.m2 -> appveyor.yml

configuration: Release

before_build:
  - ps: ./appveyor_before_build.ps1
  - nuget restore
  
build:
  verbosity: minimal
  project: SonarQube.Scanner.MSBuild.sln
 
on_success:
  - ps: ./appveyor_on_success.ps1

on_finish:
# Uncomment this to be able to RDP into the build agent
# ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false

