version: 1.0.{build}

environment:
  matrix:
  - Configuration: Release
  - Configuration: Debug

notifications:
- provider: HipChat
  room: 409390
  auth_token:
    secure: RW8+2GpOWo3PcoM3ehoI+mbfUr7h508RtTDyszpR6/E=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
